### ISSUE TITLE
PyAudio IOError: No Default Input Device Available

### ISSUE THREAD

**Issue by michael7908** [Olney1/ChatGPT-OpenAI-Smart-Speaker#1]
Hi I installed all the components on an AWS EC2 instance (ubuntu20) and got this error message when I run "python smart_speaker.py"

ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_id returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM dmix
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Traceback (most recent call last):
  File "/root/ChatGPT-OpenAI-Smart-Speaker/smart_speaker.py", line 68, in <module>
    main()
  File "/root/ChatGPT-OpenAI-Smart-Speaker/smart_speaker.py", line 59, in main
    prompt = recognize_speech()
  File "/root/ChatGPT-OpenAI-Smart-Speaker/smart_speaker.py", line 16, in recognize_speech
    with sr.Microphone() as source:
  File "/usr/local/lib/python3.10/dist-packages/speech_recognition/__init__.py", line 99, in __init__
    device_info = audio.get_device_info_by_index(device_index) if device_index is not None else audio.get_default_input_device_info()
  File "/usr/lib/python3/dist-packages/pyaudio.py", line 949, in get_default_input_device_info
    device_index = pa.get_default_input_device

Any idea how I can fix this?

**Comment by michael7908** [comment]
thank you very much

**Comment by Olney1** [comment]
Hi Michael, at the moment the code is designed to work on a local device as it requests permissions to access the microphone on your Mac/PC/laptop.

**Comment by michael7908** [comment]
Hi Olney,thansk for your prompt reply and i have installed your codes onto my local machine (Win10) and it worked but just threw another error message 

"Mpg321 is not recognized as an internal or external command, operable program or batch file"  ( shown in my Powershell terminal)

I failed to figure out how to fix this and could you please help again?

Thanks.

**Comment by Olney1** [comment]
You'll need to try using a different audio player for Windows. Keep in mind that the script you provided is written in python on Mac and it uses the subprocess library to run the mpg321 command, so you need to replace the mpg321 command with the command of the tool you choose to use in the function `play_audio_file()`.

Please let me know if you find a solution for Windows on here as I am unable to test on a  Windows machine.

**Comment by michael7908** [comment]
I found that under win10, you may try "Start response.mp3" it works for me and will run the Windows media player. Hope this helps.
