### ISSUE TITLE
Error Waiting for wake word...

### ISSUE THREAD

**Issue by HellsingsN7** [Olney1/ChatGPT-OpenAI-Smart-Speaker#11]
Hello! Thanks for this build!
I have a problem after launching, when "Waiting for wake word..." should work
I tried it on a USB microphone and wireless, but it doesn't even want to listen to my voice, but immediately gives an error.
I'd be grateful if you have a solution or a hint where to look.
"
Waiting for wake word...
Wake word file path: /home/xxxPython-3.12.7/ChatGPT-OpenAI-Smart-Speaker/wake_words/custom_model/Jeffers_Pi.ppn
Error with wake word detection, Porcupine or the PicoVoice Service.
"

**Comment by Olney1** [comment]
Hi, you need to visit: https://picovoice.ai/platform/porcupine/  and create a free account to get an access key. 

Finally, add the access key to your .env file: `ACCESS_KEY="KEY GOES HERE"`

**Comment by HellsingsN7** [comment]
> Hi, you need to visit: https://picovoice.ai/platform/porcupine/ and create a free account to get an access key.
> 
> Finally, add the access key to your .env file: `ACCESS_KEY="KEY GOES HERE"`
> 
> I'll improve the error handling to identify a missing key.

Hi. Thanks for the answer, my key is ok.
Replacing the query helped me:
from:
porcupine = pvporcupine.create(access_key=os.environ.get("ACCESS_KEY"), keyword_paths=[custom_wake_word_path])
to:
porcupine = pvporcupine.create(access_key="ACCESS_KEY", keyword_paths=[custom_wake_word_path])
