### ISSUE TITLE
Sound not playing with play_audio_file()

### ISSUE THREAD

**Issue by jc2409** [Olney1/ChatGPT-OpenAI-Smart-Speaker#3]
## Redefine play_audio_file() in smart_speaker.py using pydub

The initial code looks like below:
```
def play_audio_file():
    # play the audio file and wake speaking LEDs
    pixels.speak()
    # os.system("mpg321 response.mp3")
    playsound("response.mp3", block=False) # There’s an optional second argument, block, which is set to True by default. Setting it to False makes the function run asynchronously.
```

However, we can simply fix this using pydub package instead of playsound.

This is the code that works for me:
```
from pydub import AudioSegment
from pydub.playback import play

def play_audio_file():
    song = AudioSegment.from_mp3("response.mp3")
    play(song)
```

**Comment by Olney1** [comment]
Thanks for testing this. It appears that there was an issue impacting playsound on the Pi only. I have updated the code to reflect your use of pydub. `pip install pydub` You will also need ffmpeg on some Pi systems `sudo apt-get install ffmpeg`

Some users might also find that this alone does not solve the issue and you will need to install simpleaudio `pip install simpleaudio` and further Python development headers `sudo apt-get install python3-dev` for Python 3 and also `sudo apt-get install libasound2-dev` additional system libraries.

New code looks like this:

`def play_audio_file():
    # play the audio file and wake speaking LEDs
    pixels.speak()
    # Add 1 second silence due to initial buffering how pydub handles audio in memory
    silence = AudioSegment.silent(duration=1000) 
    audio_response = silence + AudioSegment.from_mp3("response.mp3")
    play(audio_response)`
